### ISSUE TITLE
VS 1898-01_01 C2, C3 Advertisements in the wrong place

### ISSUE THREAD

**Issue by JNG-blue** [pulibrary/BlueMountain#100]
http://bluemountain.princeton.edu/bluemtn-dev/cgi-bin/bluemtn?a=d&d=bmtnabf189801-01&e=-------en-20--1--txt-txIN-------

In other titles, all ads appear at the end of the structmap regardless of their placement in the issue itself, in this first issue of VS they are interspersed with the normal content.

Do you want me to move them? Doing so involves dragging the constituents in tree view in the mods and then dragging them in tree view in the structmap.

**Comment by cwulfman** [comment]
Yes, please.

**Comment by JNG-blue** [comment]
label changed to structure
