### ISSUE TITLE
run mods->structmap label script on Ver Sacrum

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/BlueMountain#257]
run the script; then update Veridian-dev

**Comment by cwulfman** [comment]
re-assign this to cliff when surgeries are done.

**Comment by JNG-blue** [comment]
does this also have the thing where we wanted to make the untitled images that have creators:

"Untitled Image by Creator"? What happened to that

**Comment by JNG-blue** [comment]
this ticket high priority for 7/8 meeting

**Comment by JNG-blue** [comment]
needs to be run before final metadata pass can be completed

**Comment by cwulfman** [comment]
I thought that had been run (a quick inspection showed titles like "untitled image by ...") I'll look into this now.

**Comment by cwulfman** [comment]
Looks like these scripts had been run before, but perhaps only on some issues? Running them now produces doubled labels, like "Untitled text by ADMINISTRATION "VER SACRUM" by ADMINISTRATION "VER SACRUM"
