### ISSUE TITLE
Pan 1895-06--01 c [ALL ISSUE] structure defects

### ISSUE THREAD

**Issue by JNG-blue** [pulibrary/BlueMountain#298]
structure defects 'ALL ISSUE'. Logical Structure problems with duplicate div IDs, will investigate and add to this ticket how many issues this occurs in. If the problem is limited will manually correct but leaving them for now.

<br /> issue: http://bluemountain.princeton.edu/bluemtn-dev/cgi-bin/bluemtn?a=d&d=bmtnabe189506-01 <br />

**Comment by JNG-blue** [comment]
occurs in 1895-06_01

**Comment by JNG-blue** [comment]
occurs in 1895-09_01

**Comment by JNG-blue** [comment]
and 1899-04_01

**Comment by JNG-blue** [comment]
1899-11_01

**Comment by JNG-blue** [comment]
Ok so far this seems to occur in 70-80% of the issues. I am going to time how long it takes to fix by hand for one issue.

**Comment by JNG-blue** [comment]
ok it took about 2 minutes to fix by hand. I'll leave the rest of them for now, cliff, but if you want me to fix them by hand it will take about 45 minutes to do all of them, just let me know here on the ticket.

**Comment by cwulfman** [comment]
If you've got a rhythm down, @JNG-blue ,  go ahead and fix them by hand, please.

**Comment by JNG-blue** [comment]
fixed all of these 07-31 or earlier by adding a "z" to the id string. No idea why it disliked the strings before.
