### ISSUE TITLE
One record lacks an OCLC number

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/BlueMountain#323]
One record lacks an OCLC number – an OCLC number isn’t required, but if one is supplied, it will ensure that your record will cluster correctly with other records submitted for this same title/OCLC number.  It looks like your holdings are set on OCLC 828891243, so it’s best if you supply that record.

**Comment by cwulfman** [comment]
I have identified 9 records whose 035 $a field doesn't contain "OCoLC":

1. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292591</controlfield>
2. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292591</controlfield>
3. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>
4. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>
5. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>
6. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>
7. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>
8. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>
9. <controlfield xmlns="http://www.loc.gov/MARC21/slim" tag="001">7292092</controlfield>

I do not know how to supply these with an OCLC number. @ma20 , could you help me?

**Comment by ma20** [comment]
Added 828891243 to bib ID 7292092.  Am unsure which OCLC number to add to 729591.  @cwulfman can you supply the proper OCLC num?

**Comment by cwulfman** [comment]
@ma20 and I fixed these in commit #d1496e93dc7d5a18be26a94b4d988688d7a05c12
