### ISSUE TITLE
improper 533

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/BlueMountain#324]
Record 202730 is the correct print description record, OCLC 1537507, however, there is a 533 in this record, which should only be used in microform description records. This isn’t a deal-breaker, but if you could remove this field, that would be best

**Comment by cwulfman** [comment]
This seems to be the record in question, but I don't see a 533. @ma20 , could you help me find it?
 
  <record>
      <leader>02065cas a22005417a 4500</leader>
      <controlfield tag="001">202730</controlfield>
      <controlfield tag="005">20140602103234.0</controlfield>
      <controlfield tag="008">831027d19151916nyuwr p       0    0eng c</controlfield>
      <datafield tag="010" ind1=" " ind2=" ">
         <subfield code="a">ca 19000195 </subfield>
         <subfield code="z">sn 88036976 </subfield>
      </datafield>
      <datafield tag="012" ind1=" " ind2=" ">
         <subfield code="i">8807</subfield>
      </datafield>
      <datafield tag="016" ind1="7" ind2=" ">
         <subfield code="a">013914156</subfield>
         <subfield code="2">Uk</subfield>
      </datafield>
      <datafield tag="029" ind1="1" ind2=" ">
         <subfield code="a">AU@</subfield>
         <subfield code="b">000005998851</subfield>
      </datafield>
      <datafield tag="035" ind1=" " ind2=" ">
         <subfield code="a">(CStRLIN)NJPG83-S4716</subfield>
      </datafield>
      <datafield tag="035" ind1=" " ind2=" ">
         <subfield code="9">ABB7684TS</subfield>
      </datafield>
      <datafield tag="035" ind1=" " ind2=" ">
         <subfield code="a">(OCoLC)1537507</subfield>
      </datafield>
      <datafield tag="040" ind1=" " ind2=" ">
         <subfield code="a">MUL</subfield>
         <subfield code="b">eng</subfield>
         <subfield code="c">MUL</subfield>
         <subfield code="d">NYG</subfield>
         <subfield code="d">PIT</subfield>
         <subfield code="d">NST</subfield>
         <subfield code="d">EYM</subfield>
         <subfield code="d">PIT</subfield>
         <subfield code="d">DLC</subfield>
         <subfield code="d">IUL</subfield>
         <subfield code="d">OCLCG</subfield>
         <subfield code="d">UKMGB</subfield>
         <subfield code="d">OCLCQ</subfield>
         <subfield code="d">OCLCF</subfield>
      </datafield>
      <datafield tag="042" ind1=" " ind2=" ">
         <subfield code="a">pcc</subfield>
         <subfield code="a">premarc</subfield>
      </datafield>
      <datafield tag="043" ind1=" " ind2=" ">
         <subfield code="a">n-us-ny</subfield>
      </datafield>
      <datafield tag="049" ind1=" " ind2=" ">
         <subfield code="a">PULL</subfield>
      </datafield>
      <datafield tag="050" ind1="0" ind2="0">
         <subfield code="a">AP2</subfield>
         <subfield code="b">.B87</subfield>
      </datafield>
      <datafield tag="082" ind1="0" ind2="4">
         <subfield code="a">051</subfield>
         <subfield code="b">B898</subfield>
      </datafield>
      <datafield tag="245" ind1="0" ind2="0">
         <subfield code="a">Bruno's weekly /</subfield>
         <subfield code="c">edited by Guido Bruno in his garret on Washington Square.</subfield>
      </datafield>
      <datafield tag="260" ind1=" " ind2=" ">
         <subfield code="a">New York, N.Y. :</subfield>
         <subfield code="b">Guido Bruno,</subfield>
         <subfield code="c">1915-1916.</subfield>
      </datafield>
      <datafield tag="300" ind1=" " ind2=" ">
         <subfield code="a">v. :</subfield>
         <subfield code="b">ill. ;</subfield>
         <subfield code="c">21-29 cm.</subfield>
      </datafield>
      <datafield tag="310" ind1=" " ind2=" ">
         <subfield code="a">Weekly</subfield>
      </datafield>
      <datafield tag="362" ind1="1" ind2=" ">
         <subfield code="a">Vol. 1 (July 3, 1915)-v. 3 (Dec. 30 1916).</subfield>
      </datafield>
      <datafield tag="530" ind1=" " ind2=" ">
         <subfield code="a">Also issued on microfilm.</subfield>
      </datafield>
      <datafield tag="588" ind1=" " ind2=" ">
         <subfield code="a">Description based on: Vol. 1, no. 8, (Sept. 4, 1915); title from caption.</subfield>
      </datafield>
      <datafield tag="588" ind1=" " ind2=" ">
         <subfield code="a">Latest issue consulted: Vol. 1, no. 18 (Nov. 20th, 1915).</subfield>
      </datafield>
      <datafield tag="563" ind1=" " ind2=" ">
         <subfield code="3">Ex copy 2:</subfield>
         <subfield code="a">Original printed wrappers.</subfield>
      </datafield>
      <datafield tag="599" ind1=" " ind2=" ">
         <subfield code="a">ark:/88435/9w032569r</subfield>
         <subfield code="b">bmtnaaq_1915-07-12_01</subfield>
         <subfield code="v">vol.1,no.1 1915-07-12</subfield>
      </datafield>
      <datafield tag="650" ind1=" " ind2="0">
         <subfield code="a">American periodicals.</subfield>
      </datafield>
      <datafield tag="651" ind1=" " ind2="0">
         <subfield code="a">New York (N.Y.)</subfield>
         <subfield code="v">Periodicals.</subfield>
      </datafield>
      <datafield tag="651" ind1=" " ind2="0">
         <subfield code="a">Greenwich Village (New York, N.Y.)</subfield>
         <subfield code="v">Periodicals.</subfield>
      </datafield>
      <datafield tag="650" ind1=" " ind2="7">
         <subfield code="a">American periodicals.</subfield>
         <subfield code="2">fast</subfield>
         <subfield code="0">(OCoLC)fst00807335</subfield>
      </datafield>
      <datafield tag="651" ind1=" " ind2="7">
         <subfield code="a">New York (State)</subfield>
         <subfield code="z">New York.</subfield>
         <subfield code="2">fast</subfield>
         <subfield code="0">(OCoLC)fst01204333</subfield>
      </datafield>
      <datafield tag="651" ind1=" " ind2="7">
         <subfield code="a">New York (State)</subfield>
         <subfield code="z">New York</subfield>
         <subfield code="z">Greenwich Village.</subfield>
         <subfield code="2">fast</subfield>
         <subfield code="0">(OCoLC)fst01322891</subfield>
      </datafield>
      <datafield tag="655" ind1=" " ind2="7">
         <subfield code="a">Periodicals.</subfield>
         <subfield code="2">fast</subfield>
         <subfield code="0">(OCoLC)fst01411641</subfield>
      </datafield>
      <datafield tag="700" ind1="1" ind2=" ">
         <subfield code="a">Bruno, Guido,</subfield>
         <subfield code="d">1884-1942.</subfield>
      </datafield>
      <datafield tag="776" ind1="1" ind2=" ">
         <subfield code="t">Bruno's weekly</subfield>
         <subfield code="w">(DLC)sn 94082559</subfield>
         <subfield code="w">(OCoLC)8413898</subfield>
      </datafield>
      <datafield tag="780" ind1="0" ind2="0">
         <subfield code="t">Greenwich Village</subfield>
         <subfield code="w">(OCoLC)1751582</subfield>
      </datafield>
      <datafield tag="785" ind1="0" ind2="0">
         <subfield code="t">Bruno's</subfield>
         <subfield code="w">(DLC)sn 90018036</subfield>
         <subfield code="w">(OCoLC)21508988</subfield>
      </datafield>
      <datafield tag="856" ind1="4" ind2="1">
         <subfield code="u">http://arks.princeton.edu/ark:/88435/v979v445n</subfield>
      </datafield>
      <datafield tag="850" ind1=" " ind2=" ">
         <subfield code="a">DLC</subfield>
         <subfield code="a">MiU</subfield>
         <subfield code="a">PPiU</subfield>
      </datafield>
      <datafield tag="994" ind1=" " ind2=" ">
         <subfield code="a">C0</subfield>
         <subfield code="b">PUL</subfield>
      </datafield>
      <datafield tag="999" ind1=" " ind2=" ">
         <subfield code="a">202730</subfield>
      </datafield>
   </record>

**Comment by ma20** [comment]
@cwulfman This appears to be what we call a "legacy record," an older record that served as a master bib ID onto which all copies of that item--in any format--were attached.  There are four separate items attached to this record: three copies of the real McCoy in RBSC, and one microform copy stored at ReCAP.  We will need to create a new record for the microform copy, which is simple enough to do, although I do not have the authority to do it myself.  Would you like me to reach out to someone who can?

**Comment by cwulfman** [comment]
@ma20 Hathi specifically doesn't want the microfilm record -- only the print record. So they would like all stuff about the microform copy removed. Dana said I could just remove the 533 field, but I don't see a 533 field. What else do I need to do to remove the microform information?

**Comment by ma20** [comment]
@cwulfman  What's curious is that I don't see the 533 field in the record you copy+pasted above, but I do see it in the Voyager cataloging module.  My fear is that because there is an actual microfilm copy attached to this record, it won't be as simple as deleting the 533 field.  In order to reconcile this problem we would need separate Bib records for the microfilm copy and the print copy.  That way we retain all the forms of media in the searchable catalog and we get you a clean, print-specific record to send to Hathi.  This is an easy thing to do; I just have to get someone to do it.

**Comment by cwulfman** [comment]
Done
