### ISSUE TITLE
L'Elan (bmtnaaf) 1915-05-15-01 VIAF

### ISSUE THREAD

**Issue by ma20** [pulibrary/BlueMountain#50]
getting error messages every time I insert a VIAF ID: " E [Xerces] cvc-complex-type.3.2.2: Attribute 'valueURI' is not allowed to appear in element 'name'.  " 

Issue is in constituents 3 and 7 at time of writing.

As far as I can tell, I'm inserting it correctly--I'm following the example here:  https://github.com/pulibrary/BlueMountain/wiki/Reference#623-relateditem-typeconstituent

**Comment by nataliae** [comment]
Forwarding to Cliff

**Comment by cwulfman** [comment]
It's validating against an out-of-date MODS schema. Look in the top-level <mets> element and scan for "http://www.loc.gov/standards/mods/v3/mods-3-3.xsd" in the xsi:schemaLocation attribute; replace it with http://www.loc.gov/standards/mods/v3/mods-3-5.xsd
