### ISSUE TITLE
L'Elan (bmtnaaf) 1915-06-01_01 Missing information 

### ISSUE THREAD

**Issue by tanvisol** [pulibrary/BlueMountain#52]
The title info ("Mais ni Tete ni Bras") is not coded at all. I did add the name of the artist to the constituent and instead of 'untitled image' titled it as the above, but not sure if the above should in fact be labeled as "title." 

http://bluemountain.princeton.edu/bluemtn/cgi-bin/bluemtn?a=d&d=bmtnaaf19150601-01&e=-------en-20--1--txt-txIN-------#

**Comment by cwulfman** [comment]
Fixed title of issue to be l'elan and made the title of the cover images 'un bel elan mais ni tete ni bras'
