### ISSUE TITLE
bmtnabs: alto files not recognized on Veridian import

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/BlueMountain#63]
> WARNING: No plugin could recognise import/bmtnabs/bmtnabs/1920/06_01/alto/bmtnabs_1920-06_01_0032.alto.xml
WARNING: No plugin could recognise import/bmtnabs/bmtnabs/1920/06_01/alto/bmtnabs_1920-06_01_0031.alto.xml
WARNING: No plugin could recognise import/bmtnabs/bmtnabs/1920/06_01/alto/bmtnabs_1920-06_01_0023.alto.xml
WARNING: No plugin could recognise import/bmtnabs/bmtnabs/1920/06_01/alto/bmtnabs_1920-06_01_0022.alto.xml

**Comment by JNG-blue** [comment]
I investigated.

That "issue" does not have a mets.xml file. 

The alto xml files appear to be identical (after comparing the first two alto files) to those in:

**metadata\periodicals\bmtnabs\issues\1920\06\17_01\alto**

I think you can entirely delete the 06_01 folder as it is just another copy of the june 17th issue.

**Comment by cwulfman** [comment]
Veridian's Import-Batch script still rejects 222 out of 242 issues because of problems with the alto files.  A sample error:

> WARNING: No plugin could recognise import/bmtnabs/bmtnabs/1922/03_01/alto/bmtnabs_1922-03_01_0025.alto.xml

**Comment by JNG-blue** [comment]
Those are having the same issue as the first issue, there is no mets.alto file in the folder.  For each of them there are two hypothetical issue folders with the same alto information, but only one of them has a mets file:

06, and 06_01
08 and 08_01
03 and 03_01

**Comment by JNG-blue** [comment]
is it possible to look back at what the folders looked like when you initially committed der gegner to the dev server?

Something weird has happened since then.

**Comment by cwulfman** [comment]
I'll take a look.

**Comment by JNG-blue** [comment]
were folders renamed by one person but another person was working on them so they just got duplicated in the github rather than renamed?

**Comment by JNG-blue** [comment]
I know there were a lot of issues with the german titles to begin with

**Comment by cwulfman** [comment]
Turns out this problem has been around for a while; see <https://cdhatp.atlassian.net/projects/LETA01/issues/LETA01-111>
