### ISSUE TITLE
Sturm 1910-08-11  c009 - probable typo in the name

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/BlueMountain#80]
"Otto Spyka" is almost certainly a typo for "Otto Soyka" a common contributor. 

Issue link:

http://bluemountain.princeton.edu/bluemtn/cgi-bin/bluemtn?a=d&d=bmtnabg19100811-01&e=-------en-20--1--txt-txIN-------#

**Comment by JNG-blue** [comment]
unnecessary to check this one, added the correct viaf ID while preserving the typo in the displayname
